name: Magisk Test

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Magisk artifacts
    runs-on: ubuntu-latest
    env:
      SCCACHE_DIRECT: false
    strategy:
      fail-fast: false
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          repository: "5ec1cff/Mygisk"
          ssh-key: "${{ secrets.SSH_KEY }}"
          submodules: "recursive"
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Build debug
        run: ./build.py -v all

      - name: Stop gradle daemon
        run: ./gradlew --stop

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}
          path: out
          compression-level: 9

  test:
    name: Test on API ${{ matrix.api }}
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        api: [23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34]

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          repository: "5ec1cff/Mygisk"
          ssh-key: "${{ secrets.SSH_KEY }}"
          fetch-depth: 0

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.sha }}
          path: out

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: AVD test
        run: scripts/avd_test.sh ${{ matrix.api }}